// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhTSRaBb0wr5zbwWv33jnjGr0v9ptv4ME',
    appId: '1:147502081550:web:4340201ae7ef5970d77e5f',
    messagingSenderId: '147502081550',
    projectId: 'sipatka-f718e',
    authDomain: 'sipatka-f718e.firebaseapp.com',
    storageBucket: 'sipatka-f718e.firebasestorage.app',
    measurementId: 'G-JFB88CEJJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiI10d2F7-sXjb1iDNYSYBkutzLEWMLUY',
    appId: '1:147502081550:android:6621403786d56ad7d77e5f',
    messagingSenderId: '147502081550',
    projectId: 'sipatka-f718e',
    storageBucket: 'sipatka-f718e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVWX2BMJ9HhdVmTdlrJX3aJOYUl5oaOIU',
    appId: '1:147502081550:ios:7c6e35a51daacaf8d77e5f',
    messagingSenderId: '147502081550',
    projectId: 'sipatka-f718e',
    storageBucket: 'sipatka-f718e.firebasestorage.app',
    iosBundleId: 'com.example.sipatka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVWX2BMJ9HhdVmTdlrJX3aJOYUl5oaOIU',
    appId: '1:147502081550:ios:7c6e35a51daacaf8d77e5f',
    messagingSenderId: '147502081550',
    projectId: 'sipatka-f718e',
    storageBucket: 'sipatka-f718e.firebasestorage.app',
    iosBundleId: 'com.example.sipatka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhTSRaBb0wr5zbwWv33jnjGr0v9ptv4ME',
    appId: '1:147502081550:web:80c0f9b33a6f0517d77e5f',
    messagingSenderId: '147502081550',
    projectId: 'sipatka-f718e',
    authDomain: 'sipatka-f718e.firebaseapp.com',
    storageBucket: 'sipatka-f718e.firebasestorage.app',
    measurementId: 'G-WXZTPJZE4Z',
  );

}